version: "3.7"
services:
  #  db:
  #    container_name: user-postgres
  #    image: postgres
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #      POSTGRES_DB: tour
  #    ports:
  #      - "5433:5433"
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendOnly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/var/lib/redis/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  springapp:
    container_name: springApp
    build: .
    ports:
      - "8080:8080"
    #    environment:
    #      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/tour
    #      SPRING_DATASOURCE_USERNAME: root
    #      SPRING_DATASOURCE_PASSWORD: root
    #      DB_HOST: db
    depends_on:
      #        - db
      - redis
      #-rabbit

volumes:
  redis_vol: